server:
  port: 8180

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.122.19.138:33306/interface_data?useSSL=false
    username: root
    password: xenomysql
  data:
    redis:
      database: 1
      host: 47.122.19.138
      port: 36379
      password: xenoredis
      lettuce:
        timeout: 1000
        pool:
          max-total: 100
          max-active: 100
          max-wait: 1000
          max-idle: 20
          min-idle: 0
          shutdown-timeout: 1000ms
          retry:
            enabled: true
            attempts: 3
            delay: 100ms
            retryable-exceptions: java.net.SocketException
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl