server:
  port: 8180

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.71.161.47:3307/interface_data?useSSL=false
    username: root
    password: 123456
  data:
    redis:
      database: 14
      host: 81.71.161.47
      port: 6379
      password: 123456
      lettuce:
        timeout: 1000
        pool:
          max-total: 100
          max-active: 100
          max-wait: 1000
          max-idle: 20
          min-idle: 0
          shutdown-timeout: 1000ms
          retry:
            enabled: true
            attempts: 3
            delay: 100ms
            retryable-exceptions: java.net.SocketException
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl